name: Data Sync

on:
  schedule:
    - cron: '0 */6 * * *' # Checks every 6 hours
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Fetch Data
        run: |
          # Ensure directory exists
          mkdir -p raw_data

          # Smart-clone only the folders we need from senior repo
          git clone --depth 1 --filter=blob:none --sparse https://github.com/codelif/jiit-planner-cdn.git senior_repo
          cd senior_repo
          git sparse-checkout set "raw/time_tables/B.Tech 62 (btech-62)" "raw/time_tables/B.Tech 128 (btech-128)"
          cd ..

          # Find the first .xlsx in the directories and copy with new naming convention
          find "senior_repo/raw/time_tables/B.Tech 62 (btech-62)" -type f -name "*.xlsx" -print -quit | xargs -I {} cp "{}" raw_data/3-62.xlsx
          find "senior_repo/raw/time_tables/B.Tech 128 (btech-128)" -type f -name "*.xlsx" -print -quit | xargs -I {} cp "{}" raw_data/3-128.xlsx
          
          # Delete the temp clone
          rm -rf senior_repo

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: synchronize timetable data"
          title: "New Timetable Data Available"
          body: "A new timetable excel file has been detected in the upstream repo. Please review and merge to trigger parsing."
          branch: "sync-timetable-data"
          base: "main"
